Sample sentences
SunbirdAI/translation-portal pull request #8
Opened 2022-02-01 06:14 UTC by ak3ra

Added sample sentences in UI. 

TODO: 
- Make sentences selectable into the textarea

2022-02-02 04:36 UTC, ak3ra commented
@NLSanyu  I have added functionality to automatically paste the sample texts to text area for translation

2022-02-02 05:04 UTC, NLSanyu commented
> @NLSanyu I have added functionality to automatically paste the sample texts to text area for translation

Okay, I'll review today

2022-02-02 06:35 UTC, NLSanyu requested changes
Great job @ak3ra. It looks good and works well. However, please take note of the following things:

* I have noticed that when a category of sample sentences (common phrases) is chosen, that category's name appears with a dash after it, as shown in the screenshot below for the category "Socials". Is that on purpose?

<img width="298" alt="Screenshot 2022-02-02 at 09 24 29" src="https://user-images.githubusercontent.com/37118361/152105274-00e176b4-2bc2-499f-b4cc-dc502c9c7910.png">

* I have also left a comment about an issue I found in the code as part of this review, please check it out.

* **Note**: After working on the feedback, please format the HTML, CSS and JS files you updated using either default VSCode formatting or a linter (Prettier, for example). This is to ensure that we have good code quality.

2022-02-02 06:35 UTC, NLSanyu commented on js/scripts.js
> +function openCity(evt, cityName) {
What does "city" mean in this context? I see that the function name and variable "city" included

2022-02-04 10:43 UTC, NLSanyu commented
@ak3ra I see that you fixed the naming issue in the code as requested, thanks.
What about the issue with the dashes appearing on a selected sample sentence category?

2022-03-04 13:23 UTC, NLSanyu approved these changes

2022-03-04 13:23 UTC, merged